- src/map/npc.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/17](https://github.com/AoShinRO/brHades/security/code-scanning/17)
To fix the problem, we need to ensure that the format specifier in the `ShowWarning` function matches the type of the argument. Since `pos[7]-pos[6]` is of type `unsigned long`, we should use the `%lu` format specifier instead of `%d`.
- Update the format specifier in the `ShowWarning` function call on line 5678 to `%lu`.
- Ensure that similar changes are made to other `ShowWarning` calls if they also involve `unsigned long` arguments.
> Fix code scanning alert no. 17: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/31](https://github.com/AoShinRO/brHades/security/code-scanning/31)
To fix the problem, we need to ensure that the format specifier matches the type of the variable `entries`. Since `entries` is of type `unsigned long`, we should use the `%lu` format specifier, which is designed for `unsigned long` integers. This change will ensure that the `printf` function interprets the argument correctly, preventing any undefined behavior.
> Fix code scanning alert no. 31: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/30](https://github.com/AoShinRO/brHades/security/code-scanning/30)
To fix the problem, we need to ensure that the format specifier matches the type of the argument. Since `k + 1` is of type `size_t`, we should use the `%zu` format specifier, which is designed for `size_t` arguments. This change will ensure that the argument is interpreted correctly by the `printf` function.
> Fix code scanning alert no. 30: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/29](https://github.com/AoShinRO/brHades/security/code-scanning/29)
To fix the problem, we need to ensure that the format specifier matches the type of the argument. Since `columns` is of type `size_t`, we should use the `%zu` format specifier, which is specifically designed for `size_t` arguments. This change will ensure that the `printf` function interprets the argument correctly.
> Fix code scanning alert no. 29: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/28](https://github.com/AoShinRO/brHades/security/code-scanning/28)
To fix the problem, we need to ensure that the format specifier matches the type of the argument. Since `current` is of type `size_t`, we should use the `%zu` format specifier, which is specifically designed for `size_t` types. This change will ensure that the argument is correctly interpreted and displayed.
> Fix code scanning alert no. 28: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/27](https://github.com/AoShinRO/brHades/security/code-scanning/27)
To fix the problem, we need to ensure that the format specifier in the `ShowError` function matches the type of the `current` argument. Since `current` is of type `size_t`, we should use the `%zu` format specifier, which is specifically designed for `size_t` arguments.
- Change the format specifier from `%d` to `%zu` in the `ShowError` function calls.
- This change should be made in the file `src/tool/csv2yaml.cpp` at the specified lines.
> Fix code scanning alert no. 27: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/26](https://github.com/AoShinRO/brHades/security/code-scanning/26)
To fix the problem, we need to ensure that the format specifier matches the type of the argument. The `size_t` type should be printed using the `%zu` format specifier, which is specifically designed for `size_t` types. This change will ensure that the `printf` function interprets the argument correctly, preventing any undefined behavior.
> Fix code scanning alert no. 26: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/25](https://github.com/AoShinRO/brHades/security/code-scanning/25)
To fix the problem, we need to update the format specifier in the `ShowError` function call to correctly match the type of the `columns` variable. Since `columns` is of type `size_t`, the appropriate format specifier is `%zu`, which is used for `size_t` types.
> Fix code scanning alert no. 25: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/24](https://github.com/AoShinRO/brHades/security/code-scanning/24)
To fix the problem, we need to ensure that the format specifier matches the type of the variable `current`. Since `current` is of type `size_t`, we should use the `%zu` format specifier, which is specifically designed for `size_t` types. This change will ensure that the `ShowWarning` function correctly interprets the `current` variable.
> Fix code scanning alert no. 24: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/23](https://github.com/AoShinRO/brHades/security/code-scanning/23)
To fix the problem, we need to ensure that the format specifier matches the type of the variable being passed. Since `current` is of type `size_t`, we should use the `%zu` format specifier, which is specifically for `size_t` type variables. This change will ensure that the `ShowWarning` function correctly interprets the `current` variable.
> Fix code scanning alert no. 23: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/22](https://github.com/AoShinRO/brHades/security/code-scanning/22)
To fix the problem, we need to ensure that the format specifier matches the type of the variable being printed. Since `current` is of type `size_t`, we should use the `%zu` format specifier, which is specifically for `size_t` type.
- Change the format specifier from `%d` to `%zu` for the `current` variable in the `ShowWarning` function calls.
- This change should be made on lines 4958 and 4961.
> Fix code scanning alert no. 22: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/21](https://github.com/AoShinRO/brHades/security/code-scanning/21)
To fix the problem, we need to ensure that the format specifier matches the type of the variable being passed. Since `current` is of type `size_t`, we should use the `%zu` format specifier, which is specifically for `size_t` type.
- Change the format specifier from `%d` to `%zu` for the `current` variable in the `ShowWarning` function calls.
- This change should be made in the file `src/tool/csv2yaml.cpp` at lines 4958 and 4961.
> Fix code scanning alert no. 21: Wrong type of arguments to formatting function

- src/tool/csv2yaml.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/20](https://github.com/AoShinRO/brHades/security/code-scanning/20)
To fix the problem, we need to ensure that the type of the loop variable `i` is at least as wide as the type of `columns`. The best way to achieve this is to change the type of `i` from `uint16` to `size_t`, which matches the type of `columns`. This change will prevent any potential overflow issues and ensure that the comparison is valid.
**Steps to fix:**
1. Change the type of the loop variable `i` from `uint16` to `size_t` in the `mob_readdb_race2` function.
> Fix code scanning alert no. 20: Comparison of narrow type with wide type in loop condition

- src/map/mob.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/14](https://github.com/AoShinRO/brHades/security/code-scanning/14)
To fix the problem, we need to ensure that the format specifier matches the type of the variable `current`. Since `current` is of type `unsigned long`, we should use the `%lu` format specifier, which is designed for `unsigned long` integers.
- Change the format specifier from `%d` to `%lu` in the `ShowError` function call on line 6006.
- This change ensures that the `unsigned long` value of `current` is correctly formatted and displayed.
> Fix code scanning alert no. 14: Wrong type of arguments to formatting function

- src/map/npc.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/18](https://github.com/AoShinRO/brHades/security/code-scanning/18)
To fix the problem, we need to ensure that the format specifier matches the type of the argument. Since `pos[1]-pos[8]` is of type `unsigned long`, we should use the `%lu` format specifier, which is designed for `unsigned long` values. This change will ensure that the `ShowWarning` function correctly interprets the argument.
> Fix code scanning alert no. 18: Wrong type of arguments to formatting function

- src/map/npc.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/16](https://github.com/AoShinRO/brHades/security/code-scanning/16)
To fix the problem, we need to ensure that the format specifier matches the type of the argument. Since `pos[5]-pos[4]` is of type `size_t`, we should use the `%zu` format specifier, which is designed for `size_t` arguments. This change will ensure that the `ShowWarning` function correctly interprets the argument.
> Fix code scanning alert no. 16: Wrong type of arguments to formatting function

- src/map/npc.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/15](https://github.com/AoShinRO/brHades/security/code-scanning/15)
To fix the problem, we need to change the format specifier from `%d` to `%zu`, which is the correct format specifier for `size_t` in C++. This change ensures that the type of the argument matches the expected type of the format specifier, preventing any potential issues related to type mismatches.
> Fix code scanning alert no. 15: Wrong type of arguments to formatting function

- src/map/clif.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/13](https://github.com/AoShinRO/brHades/security/code-scanning/13)
To fix the problem, we need to ensure that the format specifier matches the type of the variable `len`, which is `size_t`. The correct format specifier for `size_t` is `%zu`. We will replace `%d` with `%zu` in the `ShowWarning` function call.
> Fix code scanning alert no. 13: Wrong type of arguments to formatting function

- src/map/clif.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/12](https://github.com/AoShinRO/brHades/security/code-scanning/12)
To fix the problem, we need to update the format specifiers in the `ShowWarning` function call to match the types of the arguments being passed. Specifically:
1. Use `%zu` for `size_t` type arguments (`len` and `sizeof(buf)-5`).
2. Verify the type of `src->id` and use the appropriate format specifier.
> Fix code scanning alert no. 12: Wrong type of arguments to formatting function

- src/common/strlib.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/11](https://github.com/AoShinRO/brHades/security/code-scanning/11)
To fix the problem, we need to ensure that the format specifier matches the type of the `entries` variable. Since `entries` is of type `size_t`, the correct format specifier to use is `%zu`, which is specifically for `size_t` types. This change will ensure that the `ShowStatus` function correctly interprets the `entries` variable.
> Fix code scanning alert no. 11: Wrong type of arguments to formatting function

- src/common/strlib.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/9](https://github.com/AoShinRO/brHades/security/code-scanning/9)
To fix the problem, we need to ensure that the format specifier matches the type of the argument being passed. In this case, `maxcols` is of type `unsigned long`, so we should use the `%lu` format specifier instead of `%d`. This change should be applied to all instances where `maxcols` is used in a `ShowError` call.
> Fix code scanning alert no. 9: Wrong type of arguments to formatting function

- src/common/strlib.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/7](https://github.com/AoShinRO/brHades/security/code-scanning/7)
To fix the problem, we need to ensure that the format specifier in the `ShowError` function matches the type of the `mincols` argument. Since `mincols` is identified as an `unsigned long`, we should use the `%lu` format specifier, which is appropriate for `unsigned long` types.
- Update the format specifier in the `ShowError` function call on line 935 to `%lu`.
- Verify and update any other instances where `mincols` is used with a format specifier to ensure consistency.
> Fix code scanning alert no. 7: Wrong type of arguments to formatting function

- src/map/script.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/5](https://github.com/AoShinRO/brHades/security/code-scanning/5)
To fix the problem, we need to ensure that the return value of `sscanf` is checked against the expected number of arguments rather than just zero. Specifically, we should check if the return value is less than the expected number of matches or if it is `EOF`. This will ensure that all possible return values are handled correctly.
In the provided code, there are two instances of `sscanf` that need to be fixed. We will update the checks to ensure they handle `EOF` and the expected number of matches correctly.
> Fix code scanning alert no. 5: Incorrect return-value check for a 'scanf'-like function

- src/map/script.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/4](https://github.com/AoShinRO/brHades/security/code-scanning/4)
To fix the problem, we need to ensure that the return value of `sscanf` is checked against the expected number of items to be read, and handle the `EOF` case appropriately. Specifically, we should:
1. Check if the return value of `sscanf` is equal to the expected number of items (1 for strings and 1 for numbers in this case).
2. Handle the case where `sscanf` returns `EOF` by breaking out of the loop or handling the error as needed.
> Fix code scanning alert no. 4: Incorrect return-value check for a 'scanf'-like function

- src/common/core.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/3](https://github.com/AoShinRO/brHades/security/code-scanning/3)
To fix the problem, we need to ensure that the return value of `sscanf` is checked against the expected number of arguments rather than just being non-zero. Specifically, we should check if `sscanf` returns 1, which indicates that one item was successfully read and assigned. Additionally, we should handle the case where `sscanf` returns `EOF`.
- Modify the return value check of `sscanf` on line 275.
- Ensure that the code handles the case where `sscanf` returns `EOF`.
> Fix code scanning alert no. 3: Incorrect return-value check for a 'scanf'-like function

- src/common/strlib.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/6](https://github.com/AoShinRO/brHades/security/code-scanning/6)
To fix the problem, we need to ensure that the format specifier matches the type of the argument. The `size_t` type is typically used for sizes and counts and is an unsigned type. The correct format specifier for `size_t` is `%zu`. We will update the format specifier in the `ShowError` function calls to use `%zu` for `columns`.
> Fix code scanning alert no. 6: Wrong type of arguments to formatting function

- src/common/strlib.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/8](https://github.com/AoShinRO/brHades/security/code-scanning/8)
To fix the problem, we need to ensure that the format specifier matches the type of the argument. Since `columns` is of type `size_t`, we should use the `%zu` format specifier, which is specifically designed for `size_t` arguments. This change will ensure that the `printf` function interprets the argument correctly, preventing any undefined behavior.
> Fix code scanning alert no. 8: Wrong type of arguments to formatting function

- src/map/atcommand.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/1245](https://github.com/AoShinRO/brHades/security/code-scanning/1245)
To fix the problem, we should replace the unsafe `strcat` calls with `strncat`, which allows us to specify the maximum number of characters to append, thus preventing buffer overflow. We need to calculate the remaining space in the buffer before each concatenation and ensure that we do not exceed `CHAT_SIZE_MAX`.
1. Replace `strcat` with `strncat` to ensure that the buffer size is not exceeded.
2. Calculate the remaining space in the buffer before each concatenation.
3. Ensure that the total length of the concatenated string does not exceed `CHAT_SIZE_MAX`.
> Fix code scanning alert no. 1245: Potentially unsafe use of strcat

- src/map/homunculus.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/1117](https://github.com/AoShinRO/brHades/security/code-scanning/1117)
To fix the problem, we will replace the `sprintf` call with `snprintf`, specifying the buffer size to ensure that the output is truncated if it exceeds the buffer length. This will prevent the buffer overflow. Additionally, we will define the buffer size using a preprocessor define to make the code more maintainable.
> Fix code scanning alert no. 1117: Potentially overrunning write with float to string conversion

- src/map/map.cpp
- src/map/npc.cpp
- src/map/script.cpp
- src/web/web.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/1110](https://github.com/AoShinRO/brHades/security/code-scanning/1110)
To fix the problem, we need to validate the input before using it to construct a file path. Specifically, we should ensure that the path does not contain any ".." sequences or path separators that could lead to directory traversal. We can achieve this by checking the contents of `w2` before making the recursive call to `web_config_read`.
1. Add a validation function to check for invalid sequences in the path.
2. Use this function to validate `w2` before calling `web_config_read`.
> Fix code scanning alert no. 1110: Uncontrolled data used in path expression

- src/common/grfio.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/1111](https://github.com/AoShinRO/brHades/security/code-scanning/1111)
To fix the problem, we should replace the `sprintf` calls with `snprintf` to ensure that the buffer size is not exceeded. The `snprintf` function allows us to specify the maximum number of characters to write, preventing buffer overflow. We need to update the `sprintf` calls on lines 683 and 684 to `snprintf`, specifying the size of the destination buffer.
> Fix code scanning alert no. 1111: Unbounded write

- src/common/malloc.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/1113](https://github.com/AoShinRO/brHades/security/code-scanning/1113)
To fix the problem, we should replace the `sprintf` call with `snprintf`, which allows us to specify the maximum number of characters to be written to the buffer. This will prevent buffer overflow by ensuring that the buffer is not overrun by the formatted string.
- Replace the `sprintf` call on line 659 in `src/common/malloc.cpp` with `snprintf`.
- Ensure that the size of the buffer `memmer_logfile` is passed to `snprintf` to limit the number of characters written.
> Fix code scanning alert no. 1113: Unbounded write

- src/tool/mapcache.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/1116](https://github.com/AoShinRO/brHades/security/code-scanning/1116)
To fix the problem, we should replace the `sprintf` calls with `snprintf` to ensure that the buffer size is not exceeded. This change will prevent potential buffer overflow by specifying the maximum number of characters to be written to the buffer.
- Replace `sprintf(filename, "data\\%s.gat", name);` with `snprintf(filename, sizeof(filename), "data\\%s.gat", name);`.
- Replace `sprintf(filename, "data\\%s.rsw", name);` with `snprintf(filename, sizeof(filename), "data\\%s.rsw", name);`.
These changes ensure that the formatted string will not exceed the size of the `filename` buffer.
_Suggested fixes powered by Copilot Autofix. Review carefully before …
> Fix code scanning alert no. 1116: Unbounded write

- src/map/pc.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/1115](https://github.com/AoShinRO/brHades/security/code-scanning/1115)
To fix the problem, we should replace the `sprintf` calls with `snprintf` to ensure that the buffer size is not exceeded. This will involve specifying the maximum number of characters to write to the buffer, which should be one less than the buffer size to leave room for the null terminator.
> Fix code scanning alert no. 1115: Unbounded write

- src/map/pc.cpp
Fixes [https://github.com/AoShinRO/brHades/security/code-scanning/1114](https://github.com/AoShinRO/brHades/security/code-scanning/1114)
To fix the problem, we should replace the `sprintf` calls with `snprintf` to ensure that the buffer size is not exceeded. This will involve specifying the maximum number of characters to write to the buffer, which should be the size of the buffer minus one to leave space for the null terminator.
> Fix code scanning alert no. 1114: Unbounded write

- db/pre-re/size_fix.yml
- db/re/size_fix.yml
- db/size_fix.yml
Remoção do tamanho da arma chicote e adicionado a correção.
Pré-Renewal, Renewal.
> Correção do tamanho da arma chicote #8883
