.github/workflows/build_servers_clang.yml
=> trying  fix clang  workflow

.github/workflows/build_servers_gcc.yml
=> trying_fix_gccworkflow

.github/workflows/build_servers_vip.yml
=> fixing build server in  vip mode workflow

.github/workflows/build_servers_packetversions.yml, .github/workflows/build_servers_vip.yml
=> trying solve buildpacketver

.github/workflows/Build servers with Clang.yml
=> Create Build servers with Clang.yml

src/char/char-server.vcxproj, src/login/login-server.vcxproj, src/map/map-server-generator.vcxproj, src/map/map-server.vcxproj, src/tool/csv2yaml.vcxproj, src/tool/mapcache.vcxproj, src/tool/yaml2sql.vcxproj, src/tool/yamlupgrade.vcxproj, src/web/web-server.vcxproj
=> release 32 c++20

.github/workflows/analysis_codeql.yml, .github/workflows/build_servers_clang.yml, .github/workflows/build_servers_cmake.yml, .github/workflows/build_servers_gcc.yml, .github/workflows/build_servers_modes.yml, .github/workflows/build_servers_msbuild.yml, .github/workflows/build_servers_packetversions.yml, .github/workflows/build_servers_vip.yml, .github/workflows/npc_db_validation.yml, src/common/database.cpp, src/map/map.hpp
=> codeql  try  fix again

src/char/char-server.vcxproj, src/common/common-minicore.vcxproj, src/common/common.vcxproj, src/common/database.cpp, src/login/login-server.vcxproj, src/map/map-server-generator.vcxproj, src/map/map-server.vcxproj, src/tool/csv2yaml.vcxproj, src/tool/mapcache.vcxproj, src/tool/yaml2sql.vcxproj, src/tool/yamlupgrade.vcxproj, src/web/web-server.vcxproj
=> finishing all targets to c++20

.github/workflows/analysis_codeql.yml
=> reworking codeql

.github/workflows/build_servers_clang.yml, .github/workflows/build_servers_gcc.yml, .github/workflows/build_servers_vip.yml
=> reduzindo excesso de workflows

3rdparty/httplib/httplib.vcxproj, 3rdparty/libconfig/libconfig.vcxproj, 3rdparty/rapidyaml/ryml.vcxproj, 3rdparty/yaml-cpp/yaml-cpp.vcxproj, src/char/char-server.vcxproj, src/common/common-minicore.vcxproj, src/common/common.vcxproj, src/login/login-server.vcxproj, src/map/map-server-generator.vcxproj, src/map/map-server.vcxproj, src/tool/csv2yaml.vcxproj, src/tool/mapcache.vcxproj, src/tool/yaml2sql.vcxproj, src/tool/yamlupgrade.vcxproj, src/web/web-server.vcxproj
=> melhorando compilação win32 release

src/map/battle.cpp, src/map/elemental.cpp, src/map/elemental.hpp, src/map/mercenary.cpp, src/map/mob.cpp, src/map/mob.hpp, src/map/navi.cpp, src/map/path.cpp, src/map/path.hpp, src/map/script.cpp, src/map/status.hpp
=> improved ranges

src/map/atcommand.cpp, src/map/clif.cpp, src/map/clif.hpp, src/map/clif_packetdb.hpp, src/map/guild.cpp, src/map/homunculus.cpp, src/map/mob.cpp, src/map/mob.hpp, src/map/packets.hpp, src/map/pet.cpp, src/map/script.cpp, src/map/skill.cpp, src/map/status.cpp, src/map/unit.cpp
=> PACKET_EMOTION

src/map/atcommand.cpp, src/map/clif.cpp, src/map/clif.hpp, src/map/clif_packetdb.hpp, src/map/guild.cpp, src/map/packets.hpp, src/map/pc.cpp, src/map/skill.cpp, src/map/skill.hpp, src/map/unit.cpp
=> PACKET_ZC_UPDATE_CHARSTAT

src/map/atcommand.cpp, src/map/battle.cpp, src/map/chrif.cpp, src/map/clif.cpp, src/map/clif.hpp, src/map/clif_packetdb.hpp, src/map/packets.hpp, src/map/pc.cpp, src/map/pc.hpp, src/map/script.cpp, src/map/skill.cpp, src/map/status.cpp, src/map/status.hpp, src/map/unit.cpp
=> ZC_MSG_STATE_CHANGE

db/pre-re/skill_db.yml, db/re/item_combos.yml, db/re/item_db_usable.yml, db/re/mob_db.yml, db/re/skill_db.yml, db/re/status.yml, doc/status_change.txt, src/map/battle.cpp, src/map/clif.cpp, src/map/clif_packetdb.hpp, src/map/packets.hpp, src/map/pc.cpp, src/map/script_constants.hpp, src/map/skill.cpp, src/map/status.cpp, src/map/status.hpp
=> rathenasync

src/map/npc.cpp
=> bug_fix_#79

src/common/database.cpp, src/common/database.hpp
=> limpeza na db

src/map/path.cpp
=> refatorando algoritmo a*

src/config/renewal.hpp, src/map/clif.cpp, src/map/clif.hpp, src/map/pc.cpp, src/map/pc.hpp, src/map/skill.cpp
=> restaura  animação do sonicblow/arrowvulcan

src/map/pc.cpp, src/map/skill.cpp
=> Ajuste na animação das skills

conf/battle/feature.conf, npc/other/gold_pc.txt, npc/scripts_athena.conf, src/map/battle.cpp, src/map/battle.hpp, src/map/chrif.cpp, src/map/clif.cpp, src/map/clif.hpp, src/map/clif_packetdb.hpp, src/map/map.cpp, src/map/pc.hpp
=> simples goldpc 

src/map/clif.cpp
=> disabling coin button on pvp/gvg/bg

src/common/malloc.cpp, src/map/map.cpp
=> resolvendo atualização do  goldpc points

src/map/clif.cpp, src/map/map.cpp
=> small update on gold_pc

README.md
=> Update logo link on README.md

src/map/clif.cpp
=> improved clif_bl_types

src/map/clif.cpp, src/map/clif_packetdb.hpp, src/map/packets.hpp
=> PACKET_ZC_NPCSPRITE_CHANGE

src/map/atcommand.cpp, src/map/chat.cpp, src/map/clif.cpp, src/map/clif.hpp, src/map/clif_packetdb.hpp, src/map/packets.hpp, src/map/packets_struct.hpp, src/map/pc.cpp
=> Chat pakets

conf/char_athena.conf, conf/motd.txt, src/common/cli.cpp, src/common/database.cpp, src/common/msg_conf.cpp, src/common/msg_conf.hpp, src/common/utilities.hpp, src/map/npc.cpp
=> leitura multithread npc/db

src/common/database.cpp, src/common/utilities.hpp, src/map/map.cpp, src/map/npc.cpp
=> ajustes no detailedloadingoutput

src/map/battle.cpp
=> corrigido animação miss PRE-RE custom forced animatiom

src/common/showmsg.cpp, src/common/showmsg.hpp, src/map/pc.hpp
=> smallclean+performance

src/common/db.hpp, src/map/script.cpp
=> ARR_FIND_REVERSE_IMPLEMENTED

src/common/db.cpp, src/common/utilities.hpp, src/config/core.hpp, src/map/map-server-generator.vcxproj.user, src/map/map.cpp, src/map/navi.cpp, src/map/navi.hpp, src/map/path.cpp, src/map/path.hpp
=> clean and refactor navigenerator

src/map/itemdb.cpp
=> fasting up reloaditemdb

conf/battle/client.conf, src/char/char.cpp, src/map/atcommand.cpp, src/map/battle.cpp, src/map/battle.hpp, src/map/clif.cpp, src/map/pc.cpp, src/map/status.cpp
=> bodystilefix

sql-files/main.sql, sql-files/upgrades/upgrade_20241105.sql, src/char/char.cpp, src/common/mmo.hpp, src/map/clif.cpp, src/map/clif.hpp, src/map/pc.cpp
=> costumeon&off

db/cash_emotes_db.yml, src/custom/defines_pre.hpp, src/map/clif.cpp, src/map/clif.hpp, src/map/clif_packetdb.hpp, src/map/emotes.cpp, src/map/emotes.hpp, src/map/map-server-generator.vcxproj, src/map/map-server-generator.vcxproj.filters, src/map/map-server.vcxproj, src/map/map-server.vcxproj.filters, src/map/map.cpp, src/map/packets.hpp, src/map/script_constants.hpp
=> emotes2024

src/map/clif.cpp, src/map/clif.hpp, src/map/packets.hpp, src/map/skill.cpp
=> changematerialUI

.github/workflows/build_servers_packetversions.yml, README.md, src/char/char_mapif.cpp, src/common/mmo.hpp, src/map/chrif.cpp, src/map/chrif.hpp, src/map/clif.cpp, src/map/clif.hpp, src/map/clif_packetdb.hpp, src/map/emotes.cpp, src/map/packets.hpp
=> INITIAL-RELEASE-INGAMEREPORT

src/map/clif.cpp, src/map/script.cpp
=> setbodysize+guild_join  cmd

src/map/clif.cpp
=> fix-changematerialUI

src/map/battle.cpp, src/map/clif.cpp, src/map/clif.hpp, src/map/clif_packetdb.hpp, src/map/skill.cpp
=> correção dano skillunit+miss animation

src/common/msg_conf.cpp, src/map/pc.cpp
=> inicial bugfix jobchange new client

db/mob_db.yml, db/re/item_db_etc.yml, db/re/item_db_usable.yml, db/re/mob_db.yml, db/translated/pt/item_db_re_pt.yml, db/translated/pt/re/item_db_equip.yml, db/translated/pt/re/item_db_etc.yml, db/translated/pt/re/item_db_usable.yml, db/translated/pt/re/mob_db_pt.yml, src/map/atcommand.cpp
=> tradução monstros e items

src/char/char.cpp, src/common/mmo.hpp, src/map/pc.cpp
=> [BUGfIX] Clients antigos não apareciam costume

src/common/db.cpp
=> reload_script_nullptr_bugfix

src/map/clif.cpp, src/map/npc.cpp
* **Problema(s) Tratado(s)**:https://github.com/AoShinRO/brHades/issues/174
* **Modo do Servidor**:Ambos
* **Descrição do Pull Request**:Corrige o packet baseado em sell_value
=> bug_fix_valores_na_venda_aparecendo_0

src/map/itemdb.cpp
* **Problema(s) Tratado(s)**:https://github.com/AoShinRO/brHades/pull/175
* **Modo do Servidor**:both
* **Descrição do Pull Request**:bug fix logica adicional
=> adicional_bug_fix_item_sell

.github/workflows/build_servers_cmake.yml
=> cmake_ajuste

.github/workflows/build_servers_clang.yml, README.md
=> clang_adjust

README.md
=> ajuste_discord_link

.gitignore, brHades.slnLaunch
Isso permite iniciar todos os servidores no modo de depuração automaticamente no MSVS >= 17.11
Ver https://devblogs.microsoft.com/visualstudio/multi-project-launch-configuration/ para detalhes.
=> Adicionado um perfil de lançamento de vários projetos para MSVS

src/char/char_clif.cpp
Mapas e coordenadas atualizados e acessíveis.
=> Updated accessible maps and coordinates (#8884)

db/re/map_drops.yml
* **Problema(s) Tratado(s)**: https://github.com/rathena/rathena/pull/8891
=> Added MapDrops of Horror Toy Factory #8891
